### ISSUE TITLE
Support for Sass/SCSS

### ISSUE THREAD

**Issue by rlovtangen** [uberall/grails-asset-autoprefixer#2]
The plugin works with LESS files but not with Sass/SCSS files.
Any chance to get prefixing to apply to Sass/SCSS as well?
Or if prefixing could apply to the resulting CSS from sass-asset-pipeline.

**Comment by rlovtangen** [comment]
(Twitter) Bootstrap is moving from LESS to Sass in v4 and has already (v3.2) dropped vendor prefixes in favour of adding autoprefixer to the build process. So Sass-support would be really great.

**Comment by peh** [comment]
thanks to @davydotcom and his quick fix on https://github.com/uberall/autoprefixer-asset-pipeline/pull/1 it should now work
released with version 1.3.0

**Comment by rlovtangen** [comment]
Wow, OSS FTW!
I upgraded to 1.3.0 in my example project at https://github.com/rlovtangen/asset-prefixer-sass and it seems to work fine.
Thanks!

**Comment by peh** [comment]
Cool. thank you for testing it! Yeah this proofs how nice OSS works :)
